
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.Charset;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MylesMack
 */
public class WalmartRec extends javax.swing.JFrame {

    /**
     * Creates new form WalmartRec
     */
    public WalmartRec() {
        initComponents();
        this.setBounds(0,0,jInternalFrame3.getWidth(),jInternalFrame3.getHeight());
        jInternalFrame1.setVisible(true);
        jInternalFrame3.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSearchSubmit = new javax.swing.JButton();
        jLabelItem = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldItemID10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldItemID1 = new javax.swing.JTextField();
        jTextFieldItemID2 = new javax.swing.JTextField();
        jTextFieldItemID3 = new javax.swing.JTextField();
        jTextFieldItemID4 = new javax.swing.JTextField();
        jTextFieldItemID5 = new javax.swing.JTextField();
        jTextFieldItemID6 = new javax.swing.JTextField();
        jTextFieldItemID7 = new javax.swing.JTextField();
        jTextFieldItemID8 = new javax.swing.JTextField();
        jTextFieldItemID9 = new javax.swing.JTextField();
        jLabelRating1 = new javax.swing.JLabel();
        jLabelRating2 = new javax.swing.JLabel();
        jLabelRating3 = new javax.swing.JLabel();
        jLabelRating4 = new javax.swing.JLabel();
        jLabelRating5 = new javax.swing.JLabel();
        jLabelRating6 = new javax.swing.JLabel();
        jLabelRating7 = new javax.swing.JLabel();
        jLabelRating8 = new javax.swing.JLabel();
        jLabelRating9 = new javax.swing.JLabel();
        jLabelRating10 = new javax.swing.JLabel();
        jButtonRank = new javax.swing.JButton();
        jLabelName1 = new javax.swing.JLabel();
        jLabelName2 = new javax.swing.JLabel();
        jLabelName3 = new javax.swing.JLabel();
        jLabelName4 = new javax.swing.JLabel();
        jLabelName5 = new javax.swing.JLabel();
        jLabelName6 = new javax.swing.JLabel();
        jLabelName7 = new javax.swing.JLabel();
        jLabelName8 = new javax.swing.JLabel();
        jLabelName9 = new javax.swing.JLabel();
        jLabelName10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jTextFieldSearch.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("What product would you like to look up?");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Recommendations");

        jButtonSearchSubmit.setText("Submit");
        jButtonSearchSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearchSubmit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabelItem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchSubmit))
                .addGap(36, 36, 36)
                .addComponent(jLabelItem)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jInternalFrame3.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Item#");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("ItemID");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Rating");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("#1");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("#2");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText("#3");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("#4");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setText("#5");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setText("#6");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setText("#7");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setText("#8");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setText("#9");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setText("#10");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("10 Recommendations with Rating");

        jTextFieldItemID10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID10ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel17.setText("Item Name");

        jTextFieldItemID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID1ActionPerformed(evt);
            }
        });

        jTextFieldItemID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID2ActionPerformed(evt);
            }
        });

        jTextFieldItemID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID3ActionPerformed(evt);
            }
        });

        jTextFieldItemID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID4ActionPerformed(evt);
            }
        });

        jTextFieldItemID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID5ActionPerformed(evt);
            }
        });

        jTextFieldItemID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID6ActionPerformed(evt);
            }
        });

        jTextFieldItemID7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID7ActionPerformed(evt);
            }
        });

        jTextFieldItemID8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID8ActionPerformed(evt);
            }
        });

        jTextFieldItemID9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemID9ActionPerformed(evt);
            }
        });

        jLabelRating1.setText("/5");

        jLabelRating2.setText("/5");

        jLabelRating3.setText("/5");

        jLabelRating4.setText("/5");

        jLabelRating5.setText("/5");

        jLabelRating6.setText("/5");

        jLabelRating7.setText("/5");

        jLabelRating8.setText("/5");

        jLabelRating9.setText("/5");

        jLabelRating10.setText("/5");

        jButtonRank.setText("Rate");
        jButtonRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRank)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldItemID1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldItemID10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRating1)
                            .addComponent(jLabelRating2)
                            .addComponent(jLabelRating3)
                            .addComponent(jLabelRating4)
                            .addComponent(jLabelRating5)
                            .addComponent(jLabelRating6)
                            .addComponent(jLabelRating7)
                            .addComponent(jLabelRating8)
                            .addComponent(jLabelRating9)
                            .addComponent(jLabelRating10))
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(jLabelName7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelName10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextFieldItemID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRating2))
                                    .addComponent(jLabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldItemID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelRating1)
                                    .addComponent(jLabelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextFieldItemID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRating3))
                                    .addComponent(jLabelName3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jTextFieldItemID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRating4))
                                    .addComponent(jLabelName4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTextFieldItemID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelRating6))
                                    .addComponent(jLabelName5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabelName6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel12)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabelName7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldItemID6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldItemID7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldItemID9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelRating5)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelName8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelRating7)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldItemID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelRating8)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRating9)
                            .addComponent(jLabelName9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldItemID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRating10))
                    .addComponent(jLabelName10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRank)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static String Reviews(String PR)
    {
        String review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR+"?apiKey=93dks62dn7yauy49e66e2ctd");

        int locR, locR2;
        String parseR, parseR2;
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        return review;
    }
    
    
    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    public static String callURL(String myURL) {
		//System.out.println("Requested URL:" + myURL);
		StringBuilder sb = new StringBuilder();
		URLConnection urlConn = null;
		InputStreamReader in = null;
		try {
			URL url = new URL(myURL);
			urlConn = url.openConnection();
			if (urlConn != null)
				urlConn.setReadTimeout(60 * 1000);
			if (urlConn != null && urlConn.getInputStream() != null) {
				in = new InputStreamReader(urlConn.getInputStream(),
						Charset.defaultCharset());
				BufferedReader bufferedReader = new BufferedReader(in);
				if (bufferedReader != null) {
					int cp;
					while ((cp = bufferedReader.read()) != -1) {
						sb.append((char) cp);
					}
					bufferedReader.close();
				}
			}
		in.close();
		} catch (Exception e) {
			throw new RuntimeException("Exception while calling URL:"+ myURL, e);
		} 
 
		return sb.toString();
	}
    
    
    private void jButtonSearchSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchSubmitActionPerformed

        String item;
        item = jTextFieldSearch.getText();
        String result = callURL("http://api.walmartlabs.com/v1/search?apiKey=93dks62dn7yauy49e66e2ctd&lsPublisherId={Your%20LinkShare%20Publisher%20Id}&query="+item);

        int locID;
        String parse1, parse2, itemID;
        locID=result.indexOf('[');
        parse1 = result.substring(0,locID);
        parse2 = result.substring(locID+1);
       
        locID = parse2.indexOf(':');
        parse1 = parse2.substring(locID+1);
        
        locID = parse1.indexOf(',');
        itemID = parse1.substring(0,locID);
        
        //jLabelItem. setText(itemID);
        
        result = callURL("http://api.walmartlabs.com/v1/nbp?apiKey=93dks62dn7yauy49e66e2ctd&itemId="+itemID);
        //System.out.println("You're result is " + result);
        
        //Retrieving the first 10 recommendations
        
        int count = 1;
        String i ="1";
      
        int locPR;
        String parsePR, parsePR2, resultPR, description, pubRec;
        String PR, PR2, PR3, PR4, PR5, PR6, PR7, PR8, PR9, PR10;
        
        
        
        
        locPR = result.indexOf(':');
        parsePR = result.substring(0,locPR);
        resultPR = result.substring(locPR+1);
        locPR = resultPR.indexOf(',');
        PR = resultPR.substring(0,locPR);
        description = resultPR;
        //System.out.println("Item #1: " + PR);
        Reviews(PR);
        jTextFieldItemID1.setText(PR);
        
        while(count<10)
        //for(int count = 1; count>11; count++)
        {
            locPR = resultPR.indexOf(']');
        //parsePR = resultPR.substring(0,locPR);
            parsePR = resultPR.substring(locPR+1);
            locPR = parsePR.indexOf('{');
            parsePR = parsePR.substring(locPR+1);
            locPR = parsePR.indexOf(':');
            parsePR = parsePR.substring(locPR+1);
            locPR = parsePR.indexOf(',');
            count++;
            if(count==2)
            {
                PR2 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #2: " + PR2);
                //Reviews(PR2);
                jTextFieldItemID2.setText(PR2);
            }
            if(count==3)
            {
                PR3 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #3: " + PR3);
                //Reviews(PR3); 
                jTextFieldItemID3.setText(PR3);
            }
            if(count==4)
            {
                PR4 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #4: " + PR4);
                //Reviews(PR4);
                jTextFieldItemID4.setText(PR4);
            }
            if(count==5)
            {
                PR5 = parsePR.substring(0,locPR);
                //resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #5: " + PR5);
                Reviews(PR5);
                jTextFieldItemID5.setText(PR5);
            }
            if(count==6)
            {
                PR6 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #6: " + PR6);
                //Reviews(PR6);
                jTextFieldItemID6.setText(PR6);
            }
            if(count==7)
            {
                PR7 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #7: " + PR7);
                //Reviews(PR7);
                jTextFieldItemID7.setText(PR7);
            }
            if(count==8)
            {
                PR8 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #8: " + PR8);
                //Reviews(PR8);
                jTextFieldItemID8.setText(PR8);
            }
            if(count==9)
            {
                PR9 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #9: " + PR9);
                //Reviews(PR9);
                jTextFieldItemID9.setText(PR9);
            }
            if(count==10)
            {
                PR10 = parsePR.substring(0,locPR);
                resultPR = parsePR.substring(locPR+1);
                //System.out.println("Item #10: " + PR10);
                //Reviews(PR10);
                jTextFieldItemID10.setText(PR10);
            }
            
            
        
        }
        //this.setBounds(0, 0, jInternalFrame3.getWidth(), jInternalFrame3.getHeight());
        jInternalFrame1.setVisible(false);
        jInternalFrame3.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchSubmitActionPerformed

    private void jTextFieldItemID10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID10ActionPerformed

        
    }//GEN-LAST:event_jTextFieldItemID10ActionPerformed

    private void jTextFieldItemID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID1ActionPerformed

    private void jTextFieldItemID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID2ActionPerformed

    private void jTextFieldItemID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID3ActionPerformed

    private void jTextFieldItemID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID4ActionPerformed

    private void jTextFieldItemID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID5ActionPerformed

    private void jTextFieldItemID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID6ActionPerformed

    private void jTextFieldItemID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID7ActionPerformed

    private void jTextFieldItemID8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID8ActionPerformed

    private void jTextFieldItemID9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemID9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemID9ActionPerformed

    private void jButtonRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRankActionPerformed

        String PR1, PR2, PR3, PR4, PR5, PR6, PR7, PR8, PR9, PR10, name;
        PR1 = jTextFieldItemID1.getText();
        String review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR1+"?apiKey=93dks62dn7yauy49e66e2ctd");

        int locR, locN;
        String parseR, parseR2, parseN;
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating1.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR1+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName1.setText(name);
        
        
        
        
        //rating 2
        PR2 = jTextFieldItemID2.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR2+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating2.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR2+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName2.setText(name);
        
        //rating 3
        
        PR3 = jTextFieldItemID3.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR3+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating3.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR3+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName3.setText(name);
        
        //rating 4
        
        PR4 = jTextFieldItemID4.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR4+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating4.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR4+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName4.setText(name);
        
        //rating 5
        
        PR5 = jTextFieldItemID5.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR5+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating5.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR5+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName5.setText(name);
        
        //rating 6
        
        PR6 = jTextFieldItemID6.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR6+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating6.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR6+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName6.setText(name);
        
        //rating 7
        
        PR7 = jTextFieldItemID7.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR7+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating7.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR7+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName7.setText(name);
        
        //rating 8
        
        PR8 = jTextFieldItemID8.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR8+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating8.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR8+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName8.setText(name);
        
        //rating 9
        
        PR9 = jTextFieldItemID9.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR9+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating9.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR9+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName9.setText(name);
        
        //rating 10
        
        PR10 = jTextFieldItemID10.getText();
        review = callURL("http://api.walmartlabs.com/v1/reviews/"+PR10+"?apiKey=93dks62dn7yauy49e66e2ctd");

        
        locR = review.indexOf("]");
        parseR = review.substring(locR+1);
        parseR2 = parseR;
        locR = parseR.indexOf("{");
        
        review = parseR.substring(0,locR);
        
        parseR = parseR.substring(locR+1);
        //System.out.println(review);
        if (review.equals(",\"reviewStatistics\":"))
        {
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println(review);
            
        }
        else
        {
            while(!review.equals(",\"reviewStatistics\":"))
            {
                int loc;
                
                
                
                loc = parseR2.indexOf("]");
                parseR2 = parseR2.substring(loc+1);
                loc = parseR2.indexOf("{");
                review = parseR2.substring(0,loc);
                parseR2 = parseR2.substring(loc+1);

                
                //System.out.println(parseR2);
                //System.out.println(review);
        
        /*    System.out.println("true");
            System.out.println(parseR);
            review = ",\"reviewStatistics\":";*/
            }
            locR = review.indexOf("{");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf(":");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            parseR = parseR.substring(locR+1);
            locR = parseR.indexOf("\"");
            review = parseR.substring(0, locR);
            //System.out.println("Rating: " + review);
        }
        jLabelRating10.setText(review+"/5");
        
        name = callURL("http://api.walmartlabs.com/v1/reviews/"+PR10+"?apiKey=93dks62dn7yauy49e66e2ctd");
        locN = name.indexOf(",");
        parseN = name.substring(locN+1);
        locN = parseN.indexOf(":");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        parseN = parseN.substring(locN+1);
        locN = parseN.indexOf("\"");
        name = parseN.substring(0, locN);
        jLabelName10.setText(name);
        
        Integer.parseInt(PR1);
        Integer.parseInt(PR2);
        Integer.parseInt(PR3);
        Integer.parseInt(PR4);
        Integer.parseInt(PR5);
        Integer.parseInt(PR6);
        Integer.parseInt(PR7);
        Integer.parseInt(PR8);
        Integer.parseInt(PR9);
        Integer.parseInt(PR10);
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WalmartRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WalmartRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WalmartRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WalmartRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WalmartRec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRank;
    private javax.swing.JButton jButtonSearchSubmit;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelItem;
    private javax.swing.JLabel jLabelName1;
    private javax.swing.JLabel jLabelName10;
    private javax.swing.JLabel jLabelName2;
    private javax.swing.JLabel jLabelName3;
    private javax.swing.JLabel jLabelName4;
    private javax.swing.JLabel jLabelName5;
    private javax.swing.JLabel jLabelName6;
    private javax.swing.JLabel jLabelName7;
    private javax.swing.JLabel jLabelName8;
    private javax.swing.JLabel jLabelName9;
    private javax.swing.JLabel jLabelRating1;
    private javax.swing.JLabel jLabelRating10;
    private javax.swing.JLabel jLabelRating2;
    private javax.swing.JLabel jLabelRating3;
    private javax.swing.JLabel jLabelRating4;
    private javax.swing.JLabel jLabelRating5;
    private javax.swing.JLabel jLabelRating6;
    private javax.swing.JLabel jLabelRating7;
    private javax.swing.JLabel jLabelRating8;
    private javax.swing.JLabel jLabelRating9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldItemID1;
    private javax.swing.JTextField jTextFieldItemID10;
    private javax.swing.JTextField jTextFieldItemID2;
    private javax.swing.JTextField jTextFieldItemID3;
    private javax.swing.JTextField jTextFieldItemID4;
    private javax.swing.JTextField jTextFieldItemID5;
    private javax.swing.JTextField jTextFieldItemID6;
    private javax.swing.JTextField jTextFieldItemID7;
    private javax.swing.JTextField jTextFieldItemID8;
    private javax.swing.JTextField jTextFieldItemID9;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
